### ISSUE TITLE
Two ways file sync?

### ISSUE THREAD

**Issue by MSivonen** [bitburner-official/typescript-template#7]
Is there going to be a full file sync between local and BB files?
That would be qol thing, but also remove one of the more annoying things there is and has been; if I make a certain mistake, it's instantly pushed to bb. Make a new file and rename it, for example. My bb is full of "new files". :|
Or to move files between folders by just dragging them, instead of 'mv'ing them in bb.
I know it's not a small task to ask, but it's quite easy to throw suggestions. :)

**Comment by Hoekstraa** [comment]
Please make this request at https://github.com/danielyxie/bitburner/issues,
since it requires changes mostly over there. ;)

P.S. you can turn on a feature that allows deleting files in https://github.com/bitburner-official/typescript-template/blob/main/filesync.json
